name: Cargo Build & Test

on: [push, workflow_dispatch]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: installing rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: installing cargo llvm cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: test and coeverage
        run: cargo llvm-cov
      - name: linting
        run: cargo clippy --all-targets --all-features
