name: Cargo Build & Test

on: [push, workflow_dispatch]

env: 
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly
    steps:
      - name: installing rust
      - uses: actions/checkout@v3
      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}

      - name: code coverage and test
      - uses: taiki-e/install-action@v2
        with: 
          tool: cargo-llvm-cov
      - run: cargo llvm-cov

      - name: linting
      - run: cargo clippy --all-targets --all-features
